### ISSUE TITLE
Tnt Cannons BUG

### ISSUE THREAD

**Issue by ItzWid13** [OvercastNetwork/SportBukkit#129]
Hello, overcast network developers :)
SportBukkit API is very awesome and has many advantages.
I use this API because this API can connect minecraft version - 1.7.2 ~ 1.7.10 :+1: 
so I love this very much.
but I find an error.
when i do a tnt cannon i active it
and it doesnt work,
i do a lot of tnt cannons and its bugged

**Comment by mrapple** [comment]
It's one of your plugins. Are you on peaceful?

**Comment by ItzWid13** [comment]
i download the version SportBukkit 1.7.10-RO1

**Comment by ItzWid13** [comment]
Could you compilate one for me?

**Comment by njb-said** [comment]
I believe you can get the latest version [here](https://repo.oc.tc/content/repositories/public/tc/oc/sportbukkit/1.7.10-R0.1-SNAPSHOT/)
