### ISSUE TITLE
Request: Clean up maven repository

### ISSUE THREAD

**Issue by twizmwazin** [OvercastNetwork/SportBukkit#130]
Could Overcast remove outdated builds from their maven repository? An example of what I mean is [this] (https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.7.10-R0.1-SNAPSHOT/) should only have the most recent build (and associated files) listed. Thanks

**Comment by mrapple** [comment]
That's not how maven works. The point is it keeps old builds.

**Comment by twizmwazin** [comment]
Could an easy download link be made available then? Users are going to the page to download sportbukkit and downloading dated and broken builds. I don't see a point in keeping old builds around. If someone needs an old build, they can compile it off git for themselves.

**Comment by mrapple** [comment]
Yep, it's called https://build.oc.tc

**Comment by twizmwazin** [comment]
There is no easy link to download builds without searching the build logs.

**Comment by mrapple** [comment]
Enjoy

**Comment by twizmwazin** [comment]
Thanks Apple :+1:
