### ISSUE TITLE
[Fixed] Player Damage Bug...

### ISSUE THREAD

**Issue by VegaCrystal** [OvercastNetwork/SportBukkit#134]
[This issue solved]
[I don't know how to delete this issue]

**Comment by mrapple** [comment]
You can't delete an issue. Instead of removing the original contents, it's best to just write a follow up comment

**Comment by VegaCrystal** [comment]
ok, I'll  be do next time.
but I wanna say you something.
I solved the bug, but.... the damage bug appeared again....
when I hit a player with no item in hand, he damage 2.5 ~ 3.0 heart.
this bug don't appear in the bukkit log.

**Comment by mrapple** [comment]
Unless you can provide a way to reproduce this, I'm closing this. It's probably one of your plugins.
