### ISSUE TITLE
TNT cannons doesnt work

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/SportBukkit#138]
Version: http://gyazo.com/9ad7c4de1f1c4e1931ce5d0cced5e6cb
Video proof: https://www.youtube.com/watch?v=8uI7XggnDN8

**Comment by jedediah** [comment]
When was this recorded and on what server?

**Comment by TiTo-418** [comment]
5 minutes ago, in a private server with Cardinal

**Comment by jedediah** [comment]
What private server? On our network?

**Comment by khazhyk** [comment]
does this happen on a server just running sportbukkit without any plugins? TNT cannons definitely work on our servers

**Comment by TiTo-418** [comment]
@jedediah no, in my server
@khazhyk i looking this

**Comment by jedediah** [comment]
When was the SportBukkit running on that server built? This bug was fixed over a month ago https://github.com/OvercastNetwork/SportBukkit/commit/ad97443633e9464b00628f4227109256963518d2

**Comment by TiTo-418** [comment]
I have this version: https://repo.oc.tc/service/local/repositories/snapshots/content/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150215.041225-1.jar

**Comment by jedediah** [comment]
That build is from Feb 15th, fix was made on Feb 17th.

**Comment by TiTo-418** [comment]
Ok, where can i found the lastest version?

**Comment by jedediah** [comment]
https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150325.005932-17.jar

**Comment by TiTo-418** [comment]
Thanks!

**Comment by TiTo-418** [comment]
See this: http://youtu.be/_eE0VTe0pJw

**Comment by jedediah** [comment]
That is normal behavior for 1.8. You can disable it in bukkit.yml:
```
settings:
    water-pushes-tnt: false
```

**Comment by TiTo-418** [comment]
Really?! Thanks!
