### ISSUE TITLE
How to compile SportBukkit 1.8?

### ISSUE THREAD

**Issue by elraro** [OvercastNetwork/SportBukkit#141]
Hi. Im trying compiling SportBukkit 1.8 (branch real1.8). Im following the README but it doesnt work:

alberto@albertoFijo:~/Escritorio/sportbukkit$ ./applyPatches.sh
  Rebuilding Forked projects.... 
Clonar en «build/CraftBukkit»...
hecho.
  Resetting build/CraftBukkit to base/CraftBukkit...
error: Could not remove config section 'remote.upstream'
HEAD is now at 501372f Special case record placement into juke boxes as they update their tile.
  Applying patches to build/CraftBukkit...
Resolve operation not in progress, we are not resuming.
Applying: Import necessary NMS classes
Applying: Implement the affectsSpawning API
fatal: sha1 information is lacking or useless (src/main/java/net/minecraft/server/EntityHuman.java).
Repository lacks necessary blobs to fall back on 3-way merge.
Cannot fall back to three-way merge.
Patch failed at 0002 Implement the affectsSpawning API
The copy of the patch that failed is found in:
   /home/alberto/Escritorio/sportbukkit/build/CraftBukkit/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
  Something did not apply cleanly to build/CraftBukkit.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh

**Comment by ShinyDialga45** [comment]
Since SportBukkit uses an older version of CraftBukkit 1.8, you'll need to manually go and get the version it uses. Or, you can use a python script that @twizmwazin wrote that compiles the whole thing. https://gist.github.com/twizmwazin/d68dfeff1ab54cb13896 is the link.
