### ISSUE TITLE
Tnt does apply motion to players (icraruses don't work)

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#149]
Tnt does apply motion to players (icraruses don't work)

**Comment by TheMolkaPL** [comment]
Did you read this? https://github.com/OvercastNetwork/SportBukkit/issues/138

**Comment by Pablete1234** [comment]
should be fixed. it's not. oc.tc just updated primed to the last versions, it still doesn't work

**Comment by twizmwazin** [comment]
Is this issue able to be reproduced in Vanilla 1.8?

**Comment by TiTo-418** [comment]
@twizmwazin Yes

**Comment by twizmwazin** [comment]
@TiTo-418 Than this issue isn't really valid, it is just a request for 1.7 mechanics.

**Comment by jedediah** [comment]
fixed

**Comment by Pablete1234** [comment]
i just downloaded lastest 1.8 sportbukkit version, icarues launch me like 5 blocks foward, tested in vanilla, icaruses work just like in 1.7

**Comment by Pablete1234** [comment]
by twizmwazin on #154:
" Just did some proper testing, ny_ and did some some tests with various builds.

https://www.youtube.com/watch?v=nU6UH0ZMzrM

It appears to be a CraftBukkit issue rather than a SportBukkit issue, here is the CraftBukkit issue. I figure you should know, as Overcast's gameplay is most affected by this bug."

**Comment by TiTo-418** [comment]
Fixed
