### ISSUE TITLE
Ladder placement issues

### ISSUE THREAD

**Issue by twizmwazin** [OvercastNetwork/SportBukkit#152]
Currently, if a ladder is placed in a block with a player, the action is cancelled by the server. This contrasts with the Vanilla behavior, which will only cancel it if the player's collision box intersects with the ladder's. This issue also appears in older versions of Craftbukkit, including the revision SportBukkit is currently based from. It is worth noting that issue has been resolved in CraftBukkit and Spigot, although I don't know which commit specifically.

**Comment by TiTo-418** [comment]
Fixed
