### ISSUE TITLE
Player UPDATE

### ISSUE THREAD

**Issue by ElDzi** [OvercastNetwork/SportBukkit#160]
Add methods where we can check player online mode. 
//player.isPremoum etc.

**Comment by YukonAppleGeek** [comment]
Not exactly sure why this is needed. If the server is in offline mode all players are not verified and if it is online mode they all are verified.

**Comment by TheMolkaPL** [comment]
Wut?

You can do this by the Mojang API -> http://wiki.vg/Mojang_API
It's not needed in the server engine...

**Comment by mrapple** [comment]
We're not adding this to SportBukkit.
