### ISSUE TITLE
Players are invisible when matches start

### ISSUE THREAD

**Issue by SheriffSoco** [OvercastNetwork/SportBukkit#162]
When testing maps on The Last Life, we have come across a bug in 1.8.0/1.8.1. Before the match begins, everyone is visible, but when matches start, sometimes one of the players becomes invisible and cannot be hit. When matches begin in TLL, I can post images.

**Comment by TheMolkaPL** [comment]
It's an PGM issue I think

**Comment by SheriffSoco** [comment]
It might be an optifine bug, not sure

**Comment by twizmwazin** [comment]
This is a PGM issue, sportbukkit has little to do with this. Optifine shouldn't have an effect either.

**Comment by TheMolkaPL** [comment]
Report it on the [Issues Tracker](https://github.com/OvercastNetwork/Issues/issues).

**Comment by TiTo-418** [comment]
@SheriffSoco Could you close this?
