### ISSUE TITLE
Long range TNT viewing feature is broken

### ISSUE THREAD

**Issue by Eudaldca** [OvercastNetwork/SportBukkit#163]
Basically, this used to work but broke in an update. I believe it broke in 1.8.7, but I'm not sure. To test this just hop on primed, I'm surprised there isn't an issue for this.

**Comment by CaptainElliott** [comment]
This was not a sportbukkit feature, but instead PGM - you should make an issue there.

**Comment by Eudaldca** [comment]
@CaptainElliott I thought it was a sportbukkit, as I saw the feature disappear both in my cardinal server and in overcast at the same time.

**Comment by twizmwazin** [comment]
@Eudaldca It was never a thing in Cardinal

**Comment by Eudaldca** [comment]
@twizmwazin I don't know why, but I really thought it was a thing.
