### ISSUE TITLE
I coded a TabList Plugin with SportBukkit, but I have some error.

### ISSUE THREAD

**Issue by VegaCrystal** [OvercastNetwork/SportBukkit#165]
first, this is my code.
class name> TabList.java

this is the error code.

    public void InitializePlayer(Player player) {
        ((CraftPlayer) player).getHandle().playerConnection.sendPacket(PacketPlayOutPlayerInfo.removePlayer(((CraftPlayer) player).getHandle()));
        PacketPlayOutPlayerInfo packet = new PacketPlayOutPlayerInfo();
        for(int i = 0; i < 60; i++) {
            packet.action = 0;
            GameProfile profile = new GameProfile(UUID.fromString("40f08c66-da55-4816-bd94-8ccb21446547"), this.GetNullSlotName(i));
            Entry entry = new Entry(profile.getId(), this.GetNullSlotName(i), ChatSerializer.a(CraftChatMessage.fromString(this.GetNullSlotName(i))[0]), 0, 1100, profile.getProperties());
        	
        	packet.entries = Collections.singletonList(entry);
            
            ((CraftPlayer) player).getHandle().playerConnection.sendPacket(packet);
        }
    }

This code doesn't have error.
this method fill tab slots with null strings and run in the event, PlayerJoinEvent

    public void SendTab(Player player, int index, String fakePrefix, String fakeSuffix) {
        PacketPlayOutScoreboardTeam packet = new PacketPlayOutScoreboardTeam();
        packet.a = this.GetNullSlotName(index);
        packet.b = this.GetNullSlotName(index);
        packet.c = fakePrefix;
        packet.d = fakeSuffix;
        packet.f = 2;
        packet.g = 0;
        ((CraftPlayer) player).getHandle().playerConnection.sendPacket(packet);
    }

this method have error.
when I join this server, my minecraft client crash.
the client error log: 'Expected Error' or 'Ticking screen'

How I know: If I remove it, client didn't crash.

Can i know why client crash?
and can you help me to fix?

**Comment by CaptainElliott** [comment]
This is not for technical assistance, but for reporting bugs

**Comment by TheMolkaPL** [comment]
Use markdown please.

```md
```java
public static void main(String[] args) {
    System.out.println("Hello world");
}
```
```

**Comment by VegaCrystal** [comment]
@CaptainElliott 
This is report.
When I run code with another bukkit, It works well. (but very laggy)

**Comment by mrapple** [comment]
Using NMS is at your own risk. We only provide support for the API.
