### ISSUE TITLE
Problems with commits

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#181]
commits older than f1c7d61 seem to be broken
if you try to open them, the will show an error

**Comment by jedediah** [comment]
What error, where? Where are you opening them?

**Comment by Pablete1234** [comment]
@jedediah https://github.com/OvercastNetwork/SportBukkit/commit/f9c8cf462b77da0106fb9b65e1453504d09f936f
for example, it just says "Sorry, this diff is unavailable."

**Comment by jedediah** [comment]
That's probably a commit from the old CraftBukkit repo that got a DMCA takedown

**Comment by Pablete1234** [comment]
@jedediah but most old commits have that problem

**Comment by jedediah** [comment]
Ok, yeah, commits on our own repo are giving that error. I have no idea why, probably an issue at Github.

**Comment by tonybruess** [comment]
Fixed
