### ISSUE TITLE
ProtocolTranslator throws NPE when DataWatcher item has no entity type set

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#198]
Sending player spawn packets with metadata for the skin flag only kicks 1.9 clients, but works just fine with 1.10 clients, server log:
![image](https://cloud.githubusercontent.com/assets/11789291/15969222/5caf2a56-2f2f-11e6-875f-14c009111aed.png)

**Comment by Pablete1234** [comment]
Found out the issue comes from data watcher items not having an entity type set. It would be nice to either get a constructor for DataWatcher.Item<> that includes the entity type, or try to ignore the entity type in the metadata translator if it's null, but still metadata needs to be translated (health index is 6 in 1.9 and 7 in 1.10)

**Comment by jedediah** [comment]
It's a mutable public field. I added an initial value.
