### ISSUE TITLE
Sportbukkit block lag

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#204]
Core mode changes in ocn, freeze the server for a small amount of time, this is due to craftbukkit's block place method first setting it to air, and then to the new block, it caused unnecesary light updates, and in maps like fractal descent (1 thick core all arround) it creates a lag spike on the server.

This was a bug upstream, reported [here](https://hub.spigotmc.org/jira/browse/SPIGOT-2503) that [has already been fixed upstream](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/02d704b55af439337a63becf23d8a1e05780ef01).

I think it would be good that sportbukkit either implemented the patch, or rebased to latest craft bukkit.

**Comment by jedediah** [comment]
Updated SB with the fix
