### ISSUE TITLE
Creating a patch?

### ISSUE THREAD

**Issue by sw-gw** [OvercastNetwork/SportBukkit#207]
Hi,

I'm new to this patching thing, but how would I create one?

**Comment by kblanks** [comment]
```
$ ./prepare-build.sh
# do your work
$ ./compile.sh
# test, then commit your work to each sub-repo
$ ./rebuild-patches.sh
$ git commit -am "Add stuff"
```

**Comment by sw-gw** [comment]
Was not expecting a response this quick, thanks!!

**Comment by sw-gw** [comment]
Thought I understood everything, but I ran ./prepare-build.sh, but it didn't generate any new files. Where am I supposed to commit in  @kblanks if you don't mind me asking :P

**Comment by sw-gw** [comment]
Nevermind, I just had to refresh lol.
