### ISSUE TITLE
Upgrade to JDK8

### ISSUE THREAD

**Issue by jedediah** [OvercastNetwork/SportBukkit#213]
We are considering upgrading SportBukkit to JDK8, as some features would make our patches a lot simpler e.g. interface methods.

If this is going to cause any major disruptions for anyone, speak now or forever hold your peace. I can't promise we will change our minds, but we will take it into consideration at least.

**Comment by Pablete1234** [comment]
We will be passing the warning to cardinal users:
twizmwazin/CardinalPGM@3fcd564
twizmwazin/CardinalNotifications#8

**Comment by jedediah** [comment]
mazel tav
