### ISSUE TITLE
Data watcher item casted to metadata key

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#216]
[This](https://github.com/OvercastNetwork/SportBukkit/commit/81c7063d60c7f91aba69f5e5f4bd05758bdf0179#diff-e2e769953766fe8c8776ff0a2bb7e7bfR126) is giving a class cast exception, MetadataKey extends DataWatcherObject but creating a DataWatcher.Item with a DataWatcherObject directly will cause a cast exception. A check to either cast or use id's (without translating the protocol) depending on the object type would be nice.

**Comment by jedediah** [comment]
I added the check
