### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by Uheri** [OvercastNetwork/SportBukkit#231]
Debian 7 with rake

root@SC1:/home/SportBukkit# rake default
rake aborted!
/home/SportBukkit/Rakefile:55: syntax error, unexpected tLABEL, expecting ')'
def modular_tasks(id:, name:, artifact:, work: nil)
                     ^

(See full trace by running task with --trace)
root@SC1:/home/SportBukkit#

**Comment by iPolish** [comment]
You dont have the right ruby version

**Comment by RainoBoy97** [comment]
Ruby version 2.1.5 works 👍

**Comment by Uheri** [comment]
How can I update on debian?

**Comment by iPolish** [comment]
Download the 2.1.5 version

**Comment by Uheri** [comment]
Oh yes 1.9 ;)

**Comment by Uheri** [comment]
I can not install the new version, when I do ruby ​​-v I have the 1.9.3

**Comment by Uheri** [comment]
root@play:/home/spigot/SportBukkit# rake default
git update-index -q --ignore-submodules --refresh
git diff-files --quiet --ignore-submodules --
git diff-index --cached --quiet HEAD --ignore-submodules --
Resetting to refs/remotes/upstream/upstream
git fetch upstream upstream
From /home/spigot/SportBukkit/base/Bukkit
 * branch            upstream   -> FETCH_HEAD
git reset --hard upstream/upstream
fatal: ambiguous argument 'upstream/upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
rake aborted!
Command failed with status (128): [git reset --hard upstream/upstream...]
/home/spigot/SportBukkit/utils.rb:103:in `reset'
/home/spigot/SportBukkit/Rakefile:117:in `block (3 levels) in modular_tasks'
/home/spigot/SportBukkit/Rakefile:114:in `chdir'
/home/spigot/SportBukkit/Rakefile:114:in `block (2 levels) in modular_tasks'
/home/spigot/SportBukkit/Rakefile:132:in `block (2 levels) in modular_tasks'
Tasks: TOP => bukkit:apply
(See full trace by running task with --trace)
root@play:/home/spigot/SportBukkit#

**Comment by jasoryeh** [comment]
If all fails refer to my comment on #240

**Comment by twizmwazin** [comment]
@Uheri You can install the newest version using debian backports

**Comment by Pablete1234** [comment]
since no one else has commented on this for a while i'll assume it's fixed
