### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by ianfe9** [OvercastNetwork/SportBukkit#234]
Hello everyone, when I try to compile, it appears as this:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.780s
[INFO] Finished at: Mon Feb 27 00:13:51 GMT 2017
[INFO] Final Memory: 14M/140M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sportbukkit: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Failed to collect dependencies for org.apache.maven.plugins:maven-compiler-plugin:jar:3.1 (): Failed to read artifact descriptor for org.codehaus.plexus:plexus-compiler-eclipse:jar:2.5.0-spigotmc: Could not transfer artifact org.codehaus.plexus:plexus-compiler-eclipse:pom:2.5.0-spigotmc from/to spigotmc-public (https://hub.spigotmc.org/nexus/content/groups/public/): peer not authenticated -> [Help 1]

**Comment by Pablete1234** [comment]
@ianfe9 It's not an issue on our end. Seems like you are not able to access spigot's repository, It's something you will have to fix on your end.

**Comment by twizmwazin** [comment]
If I remember correctly, this is the result of invalid ssl certificates. First, ensure Java is the latest version. If it still does not work you can try changing the repository url to http rather then https.
