### ISSUE TITLE
Sportbukkit version

### ISSUE THREAD

**Issue by AaronGamerYT12** [OvercastNetwork/SportBukkit#236]
I am have a error downloading Sportbukkit 1.8.7, server repo.oc.tc & maps.oc.tc links broken, Does anyone have the file Sportbukkit 1.8.7.jar? If you have it, can you pass it to me please?

**Comment by Pablete1234** [comment]
The old repository (repo.oc.tc) is down and the new maven repo only contains the newest jars, for older versions you will have to compile them yourself.
