### ISSUE TITLE
I can't compile too?

### ISSUE THREAD

**Issue by jasoryeh** [OvercastNetwork/SportBukkit#237]
Well I went through a lot of stuff to end up with this:

`jasor@JASON-PC:/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit$ ./compile.sh

Bukkit compiling...
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SportBukkit API 1.8-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.md-5:bungeecord-chat:jar:1.8-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.129s
[INFO] Finished at: Tue Mar 07 02:21:51 GMT 2017
[INFO] Final Memory: 7M/84M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sportbukkit-api: Could not resolve dependencies for project tc.oc:sportbukkit-
api:jar:1.8-R0.1-SNAPSHOT: Could not find artifact net.md-5:bungeecord-chat:jar:1.8-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
  Bukkit failed to compile
jasor@JASON-PC:/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit$`

**Comment by jedediah** [comment]
Current SportBukkit version is 1.11.1

**Comment by jasoryeh** [comment]
Ok. Now I end up with this after:

`Applying: Block images
Applying: Legacy protocol support
  Patches applied cleanly to build/CraftBukkit
--- Done. Now you should run ./compile.sh to proceed.
  Bukkit compiling...
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SportBukkit API 1.11-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for tc.oc:minecraft-api:jar:1.11-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.672s
[INFO] Finished at: Wed Mar 08 05:48:03 GMT 2017
[INFO] Final Memory: 8M/84M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sportbukkit-api: Could not resolve dependencies for project tc.oc:sportbukkit-
api:jar:1.11-R0.1-SNAPSHOT: Could not find artifact tc.oc:minecraft-api:jar:1.11-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
  Bukkit failed to compile`
