### ISSUE TITLE
Help on Sportbukkit please.

### ISSUE THREAD

**Issue by jasoryeh** [OvercastNetwork/SportBukkit#238]
So i've gotten to getting craftbukkit and bukkit in the base folders, now what do I do? Can someone make it a bit easier for me to understand? Like, what "work" folder there is no work folder. Also, I've tried the build script but that doesnt seem to be updated in a long time. I also seem to be getting the result in my second comment on #237

**Comment by rmsy** [comment]
What are you trying to do?

**Comment by jasoryeh** [comment]
uhm create sportbukkit

**Comment by YukonAppleGeek** [comment]
`compile.sh` does not exist in the current version of SportBukkit, please ensure you using the latest commit. Also do not create duplicate issues.

**Comment by jasoryeh** [comment]
@YukonAppleGeek I don't know how to re open but I when I got latest commit and when I run `rake` I get something else:
`
jasor@JASON-PC:/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy$ rake
[INFO] Checking out submodule base/Bukkit
git submodule update --init base/Bukkit
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:68: warning: Insecure world writable dir /home/jasor/.rvm/bin in PATH, mode 040777
Submodule 'base/Bukkit' (https://hub.spigotmc.org/stash/scm/spigot/bukkit.git) registered for path 'base/Bukkit'
Cloning into 'base/Bukkit'...
remote: Counting objects: 21789, done.
remote: Compressing objects: 100% (5557/5557), done.
remote: Total 21789 (delta 11822), reused 20503 (delta 10997)
Receiving objects: 100% (21789/21789), 2.67 MiB | 364.00 KiB/s, done.
Resolving deltas: 100% (11822/11822), done.
Checking connectivity... done.
Submodule path 'base/Bukkit': checked out '506e9411267240a81a016a47b2c093bedad50a81'
git checkout upstream
error: pathspec 'upstream' did not match any file(s) known to git.
git branch -f upstream
git checkout upstream
Switched to branch 'upstream'
git update-index -q --ignore-submodules --refresh
git diff-files --quiet --ignore-submodules --
git diff-index --cached --quiet HEAD --ignore-submodules --
[INFO] Resetting to refs/remotes/upstream/upstream
git fetch upstream +upstream:refs/remotes/upstream/upstream
fatal: Couldn't find remote ref upstream
fatal: The remote end hung up unexpectedly
rake aborted!
Command failed with status (128): [git fetch upstream +upstream:refs/remotes/...]
/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy/utils.rb:125:in `reset'
/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy/Rakefile:119:in `block (3 levels) in modular_tasks'
/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy/Rakefile:116:in `chdir'
/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy/Rakefile:116:in `block (2 levels) in modular_tasks'
/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy/Rakefile:134:in `block (2 levels) in modular_tasks'
Tasks: TOP => bukkit:apply
(See full trace by running task with --trace)
jasor@JASON-PC:/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy$ ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux-gnu]
jasor@JASON-PC:/mnt/c/Users/JasorYEH/Desktop/SportBukkit/SportBukkit - Copy$`
