### ISSUE TITLE
Unable to compile.

### ISSUE THREAD

**Issue by Hudsonlovestech** [OvercastNetwork/SportBukkit#240]
Whenever I rake my SportBukkit file this happens, what am I doing wrong?
```
Command failed with status (1): [git submodule update --init base/Bukkit...]
C:/Users/Hudson/Desktop/Rake/SportBukkit-master/utils.rb:103:in `submodule_update'
C:/Users/Hudson/Desktop/Rake/SportBukkit-master/Rakefile:104:in `block (2 levels) in modular_tasks'
Tasks: TOP => default => build/Bukkit/target/sportbukkit-api-1.11.1-R0.1-SNAPSHOT.jar => build/Bukkit => base/Bukkit
(See full trace by running task with --trace)
```

**Comment by twizmwazin** [comment]
``
(See full trace by running task with --trace)
``

**Comment by Hudsonlovestech** [comment]
Here is the output
`C:\Users\Hudson\Desktop\Rake\SportBukkit-master>rake --trace
** Invoke default (first_time)
** Invoke build/Bukkit/target/sportbukkit-api-1.11.1-R0.1-SNAPSHOT.jar (first_time)
** Invoke build/Bukkit (first_time)
** Invoke base/Bukkit (first_time)
** Execute base/Bukkit
[INFO] Checking out submodule base/Bukkit
git submodule update --init base/Bukkit
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git submodule update --init base/Bukkit...]
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
C:/Users/Hudson/Desktop/Rake/SportBukkit-master/utils.rb:103:in `submodule_update'
C:/Users/Hudson/Desktop/Rake/SportBukkit-master/Rakefile:104:in `block (2 levels) in modular_tasks'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/Ruby23/bin/rake:22:in `load'
C:/Ruby23/bin/rake:22:in `<main>'
Tasks: TOP => default => build/Bukkit/target/sportbukkit-api-1.11.1-R0.1-SNAPSHOT.jar => build/Bukkit => base/Bukkit`

**Comment by jasoryeh** [comment]
Building it usually doesn't work on Windows. Only Linux. However, you can get sportbukkit from a repo still. Let me find it.

**Comment by jasoryeh** [comment]
If you don't have a Linux machine to compile, you can get sportbukkit here: https://repo.extension.ws/
