### ISSUE TITLE
127 Failed Error on Rake

### ISSUE THREAD

**Issue by jackbear9** [OvercastNetwork/SportBukkit#242]
Got this when trying to Rake inside of Sportbukkit-master folder. Following alone with Sportbukkit GitHub page. I have done a little Googling and people say that this is caused when the command does not work properly in the line specified in the error report (utils.rb:103 and Rakefile:104).

F:\Projects\2 Project Cold Fusion\Servers\PCF\SportBukkit-master\SportBukkit-master>rake
[INFO] Checking out submodule base/Bukkit
git submodule update --init base/Bukkit
rake aborted!
Command failed with status (127): [git submodule update --init base/Bukkit...]
F:/Projects/2 Project Cold Fusion/Servers/PCF/SportBukkit-master/SportBukkit-master/utils.rb:103:in `submodule_update'
F:/Projects/2 Project Cold Fusion/Servers/PCF/SportBukkit-master/SportBukkit-master/Rakefile:104:in `block (2 levels) in modular_tasks'
Tasks: TOP => default => build/Bukkit/target/sportbukkit-api-1.11.1-R0.1-SNAPSHOT.jar => build/Bukkit => base/Bukkit
(See full trace by running task with --trace)

**Comment by jasoryeh** [comment]
Doesn't work in windows... to get sportbukkit refer to my comment on #240.

**Comment by Thrasilias** [comment]
there is a way to compile SportBukkit on Windows.

**Comment by Pablete1234** [comment]
Currently the only way is WSL or a virutal machine, alternatively you can apply the patches on linux and then copy the files over to windows and compile (compiling works, what doesn't is applying patches)

**Comment by Pablete1234** [comment]
fixed in 9671c99ba9dbff31685c72c2ccac55b85f21e7d2
