### ISSUE TITLE
Running SportBukkit

### ISSUE THREAD

**Issue by jackbear9** [OvercastNetwork/SportBukkit#244]
I am trying to run the sportbukkit jar file I have, but it throws a manifest error when using "java -jar" command in command prompt.

**Comment by jasoryeh** [comment]
java -Xms1024M -Xmx1024M -jar sportbukkit.jar ?

**Comment by jackbear9** [comment]
Still throws "no main manifest attribute, in sportbukkit-1.11.1-R0.1-20170223.091830-10.jar"

**Comment by twizmwazin** [comment]
Your sportbukkit is missing the required metadata. Try rebuilding from source.

**Comment by jackbear9** [comment]
I don't believe I can build from source on Win10. I pulled the jar from https://repo.extension.ws.

**Comment by twizmwazin** [comment]
You can build it using either WSL or in a VM. The only other option is try re-downloading, and then use the checksum to verify integrity.

**Comment by jackbear9** [comment]
Just downloaded and tried both the shaded and regular jar files. Both came back with "no main manifest..."

**Comment by twizmwazin** [comment]
Make sure you are using the sportbukkit server and not the API.

**Comment by jackbear9** [comment]
Just got the non-api version. Working now, but throwing errors. Thank you.

**Comment by jackbear9** [comment]
Fixes #244

**Comment by jasoryeh** [comment]
Please close if it is working.
