### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by VictorML11** [OvercastNetwork/SportBukkit#246]
I run "rake"
Then an error comes because the repository does not exist anymore.

Any ideas of how to solve it?
`Could not transfer artifact tc.oc:minecraft-api:pom:1.11-SNAPSHOT from/to pa-snapshots (https://repo.extension.ws/content/repositories/snapshots): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed: NotAfter: Sat Jul 14 01:54:39 CEST 2018 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by jasoryeh** [comment]
http://github.com/OvercastNetwork/minecaft-api Build that

**Comment by VictorML11** [comment]
Sorry @jasoryeh what do you mean by building that?
Isn't the problem comming because the repository does not exist?
Can you specify me more what should I do?

**Comment by jasoryeh** [comment]
In your case it looks like a certificate expired and it didn’t want to download the file, so what I mentioned was a workaround

**Comment by ryantheleach** [comment]
Do you use Avast? Avast has been known to cause issues as it MITM proxies your own connection.

**Comment by VictorML11** [comment]
Thanks that is really working. I am resolving all the failed dependencies that way. Thank you very much

**Comment by jasoryeh** [comment]
It appears the LE certificate for the maven repo expired so that’s why you got that error

**Comment by Pugzy** [comment]
@jedediah would it be possible to update the SSL on https://repo.extension.ws which would resolve this and other compilation issues on the various OCN repositories. Thanks.

**Comment by jedediah** [comment]
Certs are updated now. Did that fix it?

**Comment by Pugzy** [comment]
Managed to compile SportBukkit without any issues.

Can anyone else who had issues previously test this too.

**Comment by VictorML11** [comment]
I am getting this error:

`mkdir -p work/nms-src
[INFO] Extracting NMS classes
unzip -q temp/mapped.jar net/minecraft/server/* -d temp/classes
rake aborted!
Command failed with status (127): [unzip -q temp/mapped.jar net/minecraft/ser...]
C:/Users/victor/Desktop/AkarCraft/Nueva carpeta/SportBukkit/Rakefile:265:in `block in <top (required)>'
Tasks: TOP => default => build/CraftBukkit/target/sportbukkit-1.11.1-R0.1-SNAPSHOT.jar => build/CraftBukkit => work/CraftBukkit => work/nms-src
(See full trace by running task with --trace)`

And with --trace arg:
`[INFO] Applying CraftBukkit patches
git checkout upstream
Already on 'upstream'
Your branch is up-to-date with 'origin/upstream'.
git fetch origin upstream
From C:/Users/victor/Desktop/AkarCraft/Nueva carpeta/SportBukkit/base/CraftBukkit
 * branch              upstream   -> FETCH_HEAD
git reset --hard origin/upstream
HEAD is now at fb50a80d SPIGOT-2948: Alter filtering logic
bash applyPatches.sh ../nms-src
applyPatches.sh: line 2: $'\r': command not found
applyPatches.sh: line 15: syntax error near unexpected token `$'do\r''
'pplyPatches.sh: line 15: `do
rake aborted!
Command failed with status (2): [bash applyPatches.sh ../nms-src...]
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:57:in `sh'
C:/Users/victor/Desktop/AkarCraft/Nueva carpeta/SportBukkit/Rakefile:288:in `block (2 levels) in <top (required)>'
C:/Users/victor/Desktop/AkarCraft/Nueva carpeta/SportBukkit/Rakefile:284:in `chdir'
C:/Users/victor/Desktop/AkarCraft/Nueva carpeta/SportBukkit/Rakefile:284:in `block in <top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
C:/Ruby25-x64/bin/rake:31:in `load'
C:/Ruby25-x64/bin/rake:31:in `<main>'
Tasks: TOP => default => build/CraftBukkit/target/sportbukkit-1.11.1-R0.1-SNAPSHOT.jar => build/CraftBukkit => work/CraftBukkit`

I do not know how to solve it. Did someone have the same problem?

**Comment by Pablete1234** [comment]
Are you running it from the git-bash console?

**Comment by VictorML11** [comment]
> 
> 
> Are you running it from the git-bash console?

No I wasn't. Thank you very much now it worked fine with git-bash.

I will leave this as open just in case any other person needs help.

**Comment by Pablete1234** [comment]
This has been solved, it doesn't make sense to leave this open.
